    # The git group in use on some servers is not in Ansible yet so only append.
    - name: set groups for admin(s)
      user:
        name: "{{ item }}"
        groups: "{{ user_management_admin_groups }}"
        append: yes
      with_items: user_management_active_admins

    - name: setup authorized key(s) for root
      authorized_key:
        user: root
        key: "{{ lookup('file', user_management_ssh_keys_path ~ user_management_users[item].public_key ) }}"
      with_items: user_management_active_admins
      when: user_management_users[item].public_key is defined

    - name: setup additional authorized key(s) for root
      authorized_key:
        user: root
        key: "{{ lookup('file', user_management_ssh_keys_path ~ user_management_users[item].additional_public_key ) }}"
      with_items: user_management_active_users
      when: user_management_users[item].additional_public_key is defined


    - name: Install package sudo
      action: apt pkg=sudo state=present
