---

# handlers:
  - name: Reboot Sequence
    changed_when: true
    when: reboot_hint.stdout == "reboot"
    debug: var=reboot_hint
    notify:
      - Get Current Time
      - Reboot System
      - Wait for Server to Come Back
      - Verify Reboot Initiated

  - name: Get Current Time
    command: /bin/date +%s
    register: before_reboot
    become: false

  - name: Reboot System
    shell: sleep 2 && shutdown -r now "Rebooting now...."
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for Server to Come Back
    local_action:
      module: wait_for
         connect_timeout=10
         host={{ inventory_hostname }}
         state=started
         port=22
         delay=10
         timeout=300
    become: false

  - name: Verify Reboot Initiated
    shell: (( `date +%s` - `awk -F . '{print $1}' /proc/uptime` > {{ before_reboot.stdout }} ))
    become: false

