---
# $Author:   david_rotthoff <david_rotthoff@rotthoff.home> $
# $Date:     2017-04-09 20:41:54 -0500 $
# $Source:   roles/common/tasks/remove_source_backup.yml $

- name: copy_files - Main - Remove Source Backup File Task - Find backups files for {{ target_file }} in the target directory
  find:
    path:    "{{ copy_files_defaults.directory }}"
    pattern: "{{ item.target|default(item.source) }}.*~"
    recurse: no
  register:  files_to_remove

- name: copy_files - Main - Remove Source Backup File Task - Include debugging of main.yml
  include: remove_source_backup_debug.yml
  static:  false
  when:    copy_files_debug

- name: copy_files - Main - Remove Source Backup File Task - Removed pre-existing backup files for {{ target_file }}
  file:
    path:     "{{ path_item.path }}"
    state:    absent
  when:       files_to_remove.files is defined
  with_items: "{{ files_to_remove.files|default([]) }}"
  loop_control:
    loop_var: path_item
