---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat" or
      ansible_os_family == "Debian"

- name: Create udev rules file
  template:
    src: rules.j2
    dest: /etc/udev/rules.d/70-persistent-net.rules
  register: udev_rename_netiface_config_changed
  when: udev_rename_netiface_enabled == true
  tags:
    - udev_rename_netiface_config
