---

- name: Capture current time
  command: /bin/date +%s
  register: before_reboot
  changed_when: true

- name: Force system to reboot
  shell: sleep 2 && /sbin/shutdown -r now "Rebooting now...."
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: Wait for Server to Come Back
  local_action:
    module: wait_for
       connect_timeout=10
       host={{ inventory_hostname }}
       state=started
       port=22
       delay=10
       timeout=300
  become: false

- name: Verify the forced reboot succeeded
  shell: (( `date +%s` - `awk -F . '{print $1}' /proc/uptime` > {{ before_reboot.stdout }} ))
  register: after_reboot
