---

- name: Remove Puppet Server
  package:
    name=puppetserver
    state=absent

#- include: setservice.yml
#  vars:
#    name: puppetserver
#    state: stopped
#    enabled: false

#- include: setservice.yml
#  vars:
#    name: pxp-agent
#    state: stopped
#    enabled: false

