---
sudo: required
services: [ 'docker' ]

before_install:
- sudo docker pull centos:7

script:
- sudo docker run --detach --privileged --volume="${PWD}":/etc/ansible/roles/role:ro --name "ansible" centos:7 /usr/lib/systemd/systemd
# Check syntax of ansible playbook
- sudo docker exec "ansible" yum install -y epel-release
- sudo docker exec "ansible" yum install -y ansible
- sudo docker exec "ansible" ansible-playbook /etc/ansible/roles/role/tests/test.yml --syntax-check
- sudo docker exec "ansible" ansible-playbook /etc/ansible/roles/role/tests/test.yml
- sudo docker stop "ansible"

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
